version: '3.9'

services:
  web:
    build: .
    container_name: scanner-web
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - FERNET_KEY=${FERNET_KEY}
      - API_BASE=http://web:5000
      - DATABASE_URI=${DATABASE_URI}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    entrypoint: ["/app/entrypoint.sh"]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: scanner-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  master-worker:
    build: .
    container_name: scanner-master-worker
    environment:
      - FERNET_KEY=${FERNET_KEY}
      - API_BASE=http://web:5000
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - TRUFFLEHOG_NO_UPDATE=true
      - WORKER_TYPE=master
    command: ["python", "init_worker.py"]
    depends_on:
      - web
      - rabbitmq
    restart: always
    volumes: []  # ⛔️ prevent source code override

  worker:
    build: .
    container_name: scanner-worker
    environment:
      - FERNET_KEY=${FERNET_KEY}
      - API_BASE=http://web:5000
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - TRUFFLEHOG_NO_UPDATE=true
      - WORKER_TYPE=worker
    command: ["python", "init_worker.py"]
    depends_on:
      - web
      - rabbitmq
    restart: always
    volumes: []  # ⛔️ prevent source code override

  webhook-worker:
    build: .
    container_name: scanner-webhook-worker
    environment:
      - FERNET_KEY=${FERNET_KEY}
      - API_BASE=http://web:5000
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - TRUFFLEHOG_NO_UPDATE=true
    command: ["python", "init_webhook_worker.py"]
    depends_on:
      - web
      - rabbitmq
    restart: always
    volumes: []  # ⛔️ prevent source code override

  scheduler:
    build: .
    container_name: scanner-scheduler
    environment:
      - FERNET_KEY=${FERNET_KEY}
      - API_BASE=http://web:5000
      - DATABASE_URI=${DATABASE_URI}
    command: ["python", "run_scheduler.py"]
    depends_on:
      - web
    restart: always
    volumes: []  # ⛔️ prevent source code override
  
  uploader-worker:
    build: .
    container_name: scanner-uploader-worker
    environment:
      - FERNET_KEY=${FERNET_KEY}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - SQLITE_PATH=/app/instance/scanner.db
    command: ["python", "worker/uploader_worker.py"]
    depends_on:
      - web
      - rabbitmq
    restart: always
    volumes:
      - .:/app


