version: '3.9'

services:
  web:
    build: .
    container_name: scanner-web
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - FERNET_KEY=${FERNET_KEY}
      - API_BASE=http://web:5000
      - DATABASE_URI=${DATABASE_URI}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    command: >
      bash -c "python db_init.py && flask run --host=0.0.0.0 --port=5000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: scanner-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # management UI
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  worker:
    build: .
    environment:
      - FERNET_KEY=${FERNET_KEY}
      - API_BASE=http://web:5000
      - RABBITMQ_HOST=rabbitmq
      - TRUFFLEHOG_NO_UPDATE=true
    command: ["python", "init_worker.py"]
    depends_on:
      - web
      - rabbitmq
    restart: always
  
  scheduler:
    build: .
    environment:
      - FERNET_KEY=${FERNET_KEY}
      - API_BASE=http://web:5000
      - DATABASE_URI=${DATABASE_URI}
    depends_on:
      - web
    command: ["python", "run_scheduler.py"]
    restart: always
