apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-scanner-master-worker
spec:
  replicas: {{ .Values.replicaCount.worker.master }}
  selector:
    matchLabels:
      app: repo-scanner
      component: worker
  template:
    metadata:
      labels:
        app: repo-scanner
        component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "init_worker.py"]
          env:
            - name: WORKER_TYPE
              value: "master"
          envFrom:
            - configMapRef:
                name: repo-scanner-env
            - secretRef:
                name: repo-scanner-secret
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
