apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-scanner-webhook-worker
spec:
  replicas: {{ .Values.replicaCount.webhookWorker }}
  selector:
    matchLabels:
      app: repo-scanner
      component: webhook-worker
  template:
    metadata:
      labels:
        app: repo-scanner
        component: webhook-worker
    spec:
      containers:
        - name: webhook-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "init_webhook_worker.py"]
          envFrom:
            - configMapRef:
                name: repo-scanner-env
            - secretRef:
                name: repo-scanner-secret
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
