{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-scanner-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      component: repo-scanner
  template:
    metadata:
      labels:
        app: rabbitmq
        component: repo-scanner
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: repo-scanner-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: repo-scanner-secret
                  key: RABBITMQ_PASS
{{- end }}