{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: repo-scanner-rabbitmq
spec:
  selector:
    app: rabbitmq
    component: repo-scanner
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
{{- end }}