apiVersion: v1
kind: Secret
metadata:
  name: repo-scanner-secret
type: Opaque
stringData:
  FERNET_KEY: {{ .Values.secret.FERNET_KEY | quote }}
  DATABASE_URI: {{ .Values.secret.DATABASE_URI | quote }}
  RABBITMQ_HOST: {{ .Values.secret.RABBITMQ_HOST | quote }}
  RABBITMQ_USER: {{ .Values.secret.RABBITMQ_USER | quote }}
  RABBITMQ_PASS: {{ .Values.secret.RABBITMQ_PASS | quote }}