db_init: true

image:
  repository: bennoli13/repo-scanner
  tag: v1.0.0
  pullPolicy: IfNotPresent

replicaCount:
  web: 1
  worker: 2
  scheduler: 1

env:
  FLASK_ENV: production
  RABBITMQ_HOST: repo-scanner-rabbitmq.{Namespace}.svc.cluster.local
  API_BASE: http://repo-scanner-web.{Namespace}.svc.cluster.local:5000

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  host: {your-hostname-here}
  annotations: {}
    
rabbitmq:
  enabled: true
  image: rabbitmq:3-management

persistence:
  enabled: true
  size: 5Gi
  storageClass: gp3-retain